In [12]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np
import os

In [2]:
base_url = "https://weathernews.jp/onebox/%s/%s/"

r = requests.get(base_url%(latitude,longitude))
r.encoding = r.apparent_encoding

soup = BeautifulSoup(r.text,features="lxml")
main = soup.findAll('div',class_='weather-day')

df = []
for i in main:
    s = BeautifulSoup(str(i),features="lxml")

    #date #####################
    date = s.findAll('div',class_='weather-day__day')[0]
    date = ( BeautifulSoup(str(date),features="lxml").findAll('p') )[0]
    date = str(date)
    date = date.replace("<p>","")
    date = date.replace("</p>","")
    date = date.split(", ")[-1]
    month,day = date.split("  ")


    #header #####################
    head = s.findAll('div',class_='weather-day__head')[0]
    head = ( BeautifulSoup(str(head),features="lxml").findAll('p') )
    head = [str(h).replace("<p>","").replace("</p>","") for h in head]



    #body #####################
    body = s.findAll('div',class_='weather-day__body')[0]
    body = ( BeautifulSoup(str(body),features="lxml").findAll("div",'weather-day__item') )
    body_table = []
    for row in body:
        tmp = row.findAll('p')
        tmp = [str(a) for a in tmp]

        r = []
        r.append( tmp[0].replace("<p class=\"weather-day__time\">","").replace("</p>","") )
        r.append( tmp[1].replace("<p class=\"weather-day__icon\">","").replace("</p>","") )
        r.append( tmp[2].replace("<p class=\"weather-day__r\">","").replace("</p>","").replace("mm/h","") )
        r.append( tmp[3].replace("<p class=\"weather-day__t\">","").replace("</p>","").replace("°F","") )
        r.append( tmp[4].replace("<p class=\"weather-day__w\">","").replace("</p>","") )

        body_table.append(r)

    tmp = pd.DataFrame(columns=head,data=body_table)
    tmp["Month"] = month
    tmp["Day"] = day

    df.append(tmp)

df = pd.concat(df)
df = df[["Month","Day","Hour","Precip.","Temp."]]
df = df.rename(columns={"Precip.":"降水量（mm/h）","Temp.":"気温（°F）"})

   Month Day   Hour 降水量（mm/h） 気温（°F）
0    May   2  03:00         0     57
1    May   2  04:00         0     57
2    May   2  05:00         0     55
3    May   2  06:00         0     55
4    May   2  07:00         0     55
5    May   2  08:00         0     57
6    May   2  09:00         0     59
7    May   2  10:00         0     59
8    May   2  11:00         0     61
9    May   2  12:00         0     59
10   May   2  13:00         0     61
11   May   2  14:00         0     59
12   May   2  15:00       0.5     59
13   May   2  16:00       0.5     57
14   May   2  17:00         0     55
15   May   2  18:00         0     54
16   May   2  19:00         0     54
17   May   2  20:00         0     54
18   May   2  21:00         0     54
19   May   2  22:00         0     54
20   May   2  23:00         0     54
0    May   3  00:00         0     54
1    May   3  01:00         0     52
2    May   3  02:00         0     52
3    May   3  03:00         0     52
4    May   3  04:00         0     52
5    May   3  05:00         0     52
6    May   3  06:00         0     52
7    May   3  07:00         0     52
8    May   3  08:00         0     57
9    May   3  09:00         0     59
10   May   3  10:00         0     61
11   May   3  11:00         0     64
12   May   3  12:00         0     64